"""
arabize_pages.py - Replaces ALL English UI strings in pages.py with Arabic.
Run once: python arabize_pages.py
"""
import re

REPLACEMENTS = [
    # ── Page titles ──────────────────────────────────────────────────────────
    ('"Dashboard", "Real-time Overview"',       '"لوحة التحكم", "نظرة عامة فورية"'),
    ('"Snacks & Inventory"',                    '"المخزون والسناكس"'),
    ('"Rooms & Sessions"',                      '"الغرف والجلسات"'),
    ('"Reservations & Bookings"',               '"الحجوزات والمواعيد"'),
    ('"📅  Reservations & Bookings"',           '"📅  الحجوزات والمواعيد"'),
    ('"Expenses"',                              '"المصروفات"'),
    ('"Reports"',                               '"التقارير"'),
    ('"Sales Invoices"',                        '"فواتير المبيعات"'),
    ('"Purchase Invoices"',                     '"فواتير المشتريات"'),
    ('"Accounting & Finance"',                  '"المحاسبة والتمويل"'),
    ('"Account Statements"',                    '"كشوف الحساب"'),
    ('"Loyalty Program"',                       '"برنامج الولاء"'),
    ('"⚙️  Settings"',                          '"⚙️  الإعدادات"'),
    ('"System Configuration"',                  '"إعدادات النظام"'),

    # ── Section titles (sec_title labels) ───────────────────────────────────
    ('"▶  Start Session"',                      '"▶  بدء جلسة"'),
    ('"⏹  End Session"',                        '"⏹  إنهاء الجلسة"'),
    ('"📋  Session History"',                    '"📋  سجل الجلسات"'),
    ('"All Rooms"',                             '"جميع الغرف"'),
    ('"🏠  All Rooms"',                          '"🏠  جميع الغرف"'),
    ('"📦  Products Catalogue"',                '"📦  كتالوج المنتجات"'),
    ('"⚠️  Low Stock Alerts"',                  '"⚠️  تنبيهات نقص المخزون"'),
    ('"✏️  Edit Price & Cost"',                 '"✏️  تعديل السعر والتكلفة"'),
    ('"💸  Add Expense"',                        '"💸  إضافة مصروف"'),
    ('"📋  Expense History"',                    '"📋  سجل المصروفات"'),
    ('"🧾  Sales Invoices"',                     '"🧾  فواتير المبيعات"'),
    ('"➕  New Sales Invoice"',                  '"➕  فاتورة مبيعات جديدة"'),
    ('"📦  Purchase Invoices"',                  '"📦  فواتير المشتريات"'),
    ('"➕  New Purchase Invoice"',               '"➕  فاتورة شراء جديدة"'),
    ('"📋  Invoice Details"',                    '"📋  تفاصيل الفاتورة"'),
    ('"➕  New Booking"',                        '"➕  حجز جديد"'),
    ('"📋  All Bookings"',                       '"📋  جميع الحجوزات"'),
    ('"ℹ️  About AIS Hub"',                      '"ℹ️  عن النظام"'),
    ('"⚠️  Danger Zone"',                        '"⚠️  منطقة الخطر"'),
    ('"🔔  Notification Thresholds"',            '"🔔  حدود التنبيهات"'),
    ('"🎯  Loyalty Settings"',                   '"🎯  إعدادات الولاء"'),
    ('"📊  Revenue Overview"',                   '"📊  نظرة على الإيرادات"'),
    ('"🏆  Room Performance"',                   '"🏆  أداء الغرف"'),
    ('"📈  Sessions Overview"',                  '"📈  نظرة على الجلسات"'),
    ('"⚖️  Trial Balance"',                      '"⚖️  ميزان المراجعة"'),
    ('"📊  Balance Sheet"',                      '"📊  الميزانية العمومية"'),
    ('"📒  General Ledger"',                     '"📒  دفتر الأستاذ"'),
    ('"📓  Journal Entries"',                    '"📓  قيود اليومية"'),
    ('"📈  Income Statement"',                   '"📈  قائمة الدخل"'),
    ('"🗂️  Chart of Accounts"',                 '"🗂️  دليل الحسابات"'),
    ('"🎯  Loyalty Accounts"',                   '"🎯  حسابات الولاء"'),
    ('"🔍  Customer Lookup"',                    '"🔍  بحث العملاء"'),
    ('"👤  Customer Statements"',                '"👤  كشف حساب العميل"'),
    ('"🏭  Supplier Statements"',                '"🏭  كشف حساب المورد"'),
    ('"💎  Equity"',                             '"💎  حقوق الملكية"'),
    ('"🔴  Liabilities"',                        '"🔴  الالتزامات"'),
    ('"🟢  Assets"',                             '"🟢  الأصول"'),

    # ── Table column headers ─────────────────────────────────────────────────
    ('["#", "Room", "Type", "Customer", "People", "Started", "Elapsed"]',
     '["#", "الغرفة", "النوع", "العميل", "الأشخاص", "البداية", "المدة"]'),
    ('["#", "Room", "Type", "Status", "Price/hr", "Capacity"]',
     '["#", "الغرفة", "النوع", "الحالة", "السعر/ساعة", "السعة"]'),
    ('["#","Room","Customer","In","Out","Duration","Room Charge","Snacks","Discount","Total"]',
     '["#","الغرفة","العميل","دخول","خروج","المدة","رسوم الغرفة","سناكس","خصم","الإجمالي"]'),
    ('["SKU","Name","Category","Cost","Selling Price","Stock"]',
     '["الكود","الاسم","الفئة","التكلفة","سعر البيع","المخزون"]'),
    ('["SKU","Product","Stock"]',
     '["الكود","المنتج","المخزون"]'),
    ('["#","Date","Category","Amount","Description"]',
     '["#","التاريخ","الفئة","المبلغ","الوصف"]'),
    ('["#","Customer","Date","Total","Status"]',
     '["#","العميل","التاريخ","الإجمالي","الحالة"]'),
    ('["#","Supplier","Date","Total","Status"]',
     '["#","المورد","التاريخ","الإجمالي","الحالة"]'),
    ('["Name","Qty","Price","Total"]',
     '["الاسم","الكمية","السعر","الإجمالي"]'),
    ('["#","Entry Date","Description","Reference","Entity","Debit"]',
     '["#","التاريخ","الوصف","المرجع","الجهة","المدين"]'),
    ('["Account","Debit","Credit","Balance","Description","Date","Ref"]',
     '["الحساب","مدين","دائن","الرصيد","الوصف","التاريخ","المرجع"]'),
    ('["Account","Total Debit","Total Credit"]',
     '["الحساب","إجمالي المدين","إجمالي الدائن"]'),
    ('["Account","Balance (EGP)"]',
     '["الحساب","الرصيد (ج.م)"]'),
    ('["Code","Account","Type"]',
     '["الكود","الحساب","النوع"]'),
    ('["#","Room","Customer","Date","From","To","People","Deposit","Status"]',
     '["#","الغرفة","العميل","التاريخ","من","إلى","الأشخاص","العربون","الحالة"]'),
    ('["#","Customer","Points","Tier","Total Spent"]',
     '["#","العميل","النقاط","المستوى","الإجمالي المنفق"]'),
    ('["Invoice","Date","Amount","Status"]',
     '["الفاتورة","التاريخ","المبلغ","الحالة"]'),

    # ── Buttons ──────────────────────────────────────────────────────────────
    ('"▶  Start Session")',                     '"▶  بدء الجلسة")'),
    ('"⏹  End & Generate Bill")',               '"⏹  إنهاء وإصدار الفاتورة")'),
    ('"✏️ Edit Selected Room Price"',           '"✏️ تعديل سعر الغرفة"'),
    ('"➕ Add New Room"',                        '"➕ إضافة غرفة جديدة"'),
    ('"📄 Export Session Invoice (PDF)"',        '"📄 تصدير فاتورة الجلسة (PDF)"'),
    ('"💾  Update Price"',                       '"💾  تحديث السعر"'),
    ('"🗑  Delete Product"',                     '"🗑  حذف المنتج"'),
    ('"💾  Save Invoice"',                       '"💾  حفظ الفاتورة"'),
    ('"➕  Add Line"',                            '"➕  إضافة سطر"'),
    ('"🗑  Remove"',                              '"🗑  حذف"'),
    ('"🖨️  Export Invoice PDF"',                '"🖨️  تصدير PDF"'),
    ('"✅  Mark as Paid"',                        '"✅  تأشير مدفوع"'),
    ('"🗑  Delete Invoice"',                      '"🗑  حذف الفاتورة"'),
    ('"📅  Confirm Booking"',                    '"📅  تأكيد الحجز"'),
    ('"❌  Cancel Booking"',                     '"❌  إلغاء الحجز"'),
    ('"✏️  Edit Booking"',                       '"✏️  تعديل الحجز"'),
    ('"▶  Convert to Session"',                 '"▶  تحويل لجلسة"'),
    ('"💾  Save Settings"',                      '"💾  حفظ الإعدادات"'),
    ('"🔄  Reset Alerts"',                       '"🔄  إعادة ضبط التنبيهات"'),
    ('"📅  Start New Financial Year"',           '"📅  بدء سنة مالية جديدة"'),
    ('"➕  Add Account"',                         '"➕  إضافة حساب"'),
    ('"🔍  Lookup"',                             '"🔍  بحث"'),
    ('"💎  Redeem Points"',                      '"💎  استبدال النقاط"'),
    ('"Show All"',                              '"عرض الكل"'),
    ('"🔍 Search"',                             '"🔍 بحث"'),
    ('"Filter by Account"',                    '"تصفية حسب الحساب"'),

    # ── Form row labels ──────────────────────────────────────────────────────
    ('"Room:"',             '"الغرفة:"'),
    ('"Customer:"',         '"العميل:"'),
    ('"People:"',           '"الأشخاص:"'),
    ('"Discount (EGP):"',   '"الخصم (ج.م):"'),
    ('"Notes:"',            '"الملاحظات:"'),
    ('"Name:"',             '"الاسم:"'),
    ('"SKU:"',              '"الكود:"'),
    ('"Unit Cost:"',        '"تكلفة الوحدة:"'),
    ('"Sale Price:"',       '"سعر البيع:"'),
    ('"Category:"',         '"الفئة:"'),
    ('"Amount (EGP):"',     '"المبلغ (ج.م):"'),
    ('"Description:"',      '"الوصف:"'),
    ('"Supplier:"',         '"المورد:"'),
    ('"Product Name:"',     '"اسم المنتج:"'),
    ('"Qty:"',              '"الكمية:"'),
    ('"Selling Price:"',    '"سعر البيع:"'),
    ('"Type:"',             '"النوع:"'),
    ('"Price/hr:"',         '"السعر/ساعة:"'),
    ('"Capacity:"',         '"السعة:"'),
    ('"Description:"',      '"الوصف:"'),
    ('"Date:"',             '"التاريخ:"'),
    ('"From:"',             '"من:"'),
    ('"To:"',               '"إلى:"'),
    ('"Deposit:"',          '"العربون:"'),
    ('"Account Name:"',     '"اسم الحساب:"'),
    ('"Account Type:"',     '"نوع الحساب:"'),
    ('"Account:"',          '"الحساب:"'),
    ('"Daily Revenue Target:"', '"هدف إيرادات اليوم:"'),
    ('"Low Stock Threshold:"',  '"حد تنبيه نقص المخزون:"'),
    ('"Session Alert (hrs):"',  '"تنبيه طول الجلسة (ساعة):"'),
    ('"Unpaid Invoice Alert:"', '"تنبيه الفواتير غير المدفوعة:"'),
    ('"Points Earn Rate:"',     '"معدل كسب النقاط:"'),
    ('"Redeem Rate:"',          '"معدل الاستبدال:"'),
    ('"Promo Code:"',           '"كود الخصم:"'),
    ('"Deposit (EGP):"',        '"العربون (ج.م):"'),

    # ── Placeholder texts ────────────────────────────────────────────────────
    ('"Customer name..."',          '"اسم العميل..."'),
    ('"Customer name (editable)"',  '"اسم العميل (قابل للتعديل)"'),
    ('"Auto-filled on row select"', '"يُملأ عند الاختيار"'),
    ('"Product name (editable)"',   '"اسم المنتج (قابل للتعديل)"'),
    ('"Notes..."',                  '"ملاحظات..."'),
    ('"Search products..."',        '"بحث عن منتج..."'),
    ('"Supplier name..."',          '"اسم المورد..."'),
    ('"Customer name..."',          '"اسم العميل..."'),
    ('"Search customer..."',        '"بحث عن عميل..."'),
    ('"Search supplier..."',        '"بحث عن مورد..."'),
    ('"Account name..."',           '"اسم الحساب..."'),
    ('"e.g. Study Room C"',         '"مثال: غرفة دراسة C"'),
    ('"Optional description"',      '"وصف اختياري (اختياري)"'),

    # ── Labels / Statuses ────────────────────────────────────────────────────
    ('"Confirmed"',     '"مؤكد"'),
    ('"Cancelled"',     '"ملغي"'),
    ('"Completed"',     '"مكتمل"'),
    ('"Paid"',          '"مدفوع"'),
    ('"Unpaid"',        '"غير مدفوع"'),
    ('"Available"',     '"متاحة"'),
    ('"Occupied"',      '"مشغولة"'),
    ('"Active"',        '"نشطة"'),
    ('"Paid immediately (Cash)"', '"مدفوع نقداً"'),
    ('"Link to Session (optional):"', '"ربط بجلسة (اختياري):"'),

    # ── Stat cards ───────────────────────────────────────────────────────────
    ('"Total Rooms"',       '"إجمالي الغرف"'),
    ('"Active Sessions"',   '"الجلسات النشطة"'),
    ('"Net Profit"',        '"صافي الربح"'),
    ('"Net Loss"',          '"صافي الخسارة"'),
    ('"Today Revenue"',     '"إيرادات اليوم"'),
    ('"Total Sessions"',    '"إجمالي الجلسات"'),
    ('"Snacks Today"',      '"سناكس اليوم"'),

    # ── Total labels ─────────────────────────────────────────────────────────
    ('"Total Debit: 0.00"',     '"إجمالي المدين: 0.00"'),
    ('"Total Credit: 0.00"',    '"إجمالي الدائن: 0.00"'),
    ('"Total: 0.00"',           '"الإجمالي: 0.00"'),
    ('"Total Value: 0.00 EGP"', '"القيمة الإجمالية: 0.00 ج.م"'),
    ('"Total: 0.00"',           '"الإجمالي: 0.00"'),

    # ── Tab names ────────────────────────────────────────────────────────────
    ('"📓 Journal"',            '"📓 اليومية"'),
    ('"📒 General Ledger"',     '"📒 دفتر الأستاذ"'),
    ('"📈 Income Statement"',   '"📈 قائمة الدخل"'),
    ('"📊 Balance Sheet"',      '"📊 الميزانية"'),
    ('"⚖️ Trial Balance"',      '"⚖️ ميزان المراجعة"'),
    ('"🗂️ Chart of Accounts"',  '"🗂️ دليل الحسابات"'),
    ('"👤 Customers"',          '"👤 العملاء"'),
    ('"🏭 Suppliers"',          '"🏭 الموردون"'),

    # ── MessageBox strings ───────────────────────────────────────────────────
    ('"Select Product"',            '"اختيار منتج"'),
    ('"Click a row first."',        '"اضغط على صف أولاً."'),
    ('"Invalid"',                   '"قيمة غير صحيحة"'),
    ('"Price must be > 0."',        '"السعر يجب أن يكون أكبر من صفر."'),
    ('"Product updated."',          '"تم تحديث المنتج."'),
    ('"Select a booking."',         '"اختر حجزاً."'),
    ('"Select a booking to edit."', '"اختر حجزاً للتعديل."'),
    ('"Booking not found."',        '"الحجز غير موجود."'),
    ('"Booking updated successfully."', '"تم تحديث الحجز بنجاح."'),
    ('"Room name is required."',    '"اسم الغرفة مطلوب."'),
    ('"No available room."',        '"لا توجد غرفة متاحة."'),
    ('"Enter customer name."',      '"أدخل اسم العميل."'),
    ('"Required"',                  '"حقل مطلوب"'),
    ('"End time must be after start time."', '"وقت الانتهاء يجب أن يكون بعد وقت البداية."'),
    ('"Cannot book a past date."',  '"لا يمكن الحجز في تاريخ مضى."'),
    ('"Cannot book a past time slot."', '"لا يمكن الحجز في وقت مضى."'),
    ('"Please select a room from the table first."', '"الرجاء اختيار الغرفة من الجدول أولاً."'),
    ('"No available room in dropdown."', '"لا توجد غرفة متاحة في القائمة."'),
    ('"Error"',                     '"خطأ"'),
    ('"Enter customer name."',      '"أدخل اسم العميل."'),
    ('"Add product lines first."',  '"أضف منتجات أولاً."'),
    ('"Enter supplier name."',      '"أدخل اسم المورد."'),
    ('"Select an invoice."',        '"اختر فاتورة."'),
    ('"Account name is required."', '"اسم الحساب مطلوب."'),
    ('"Select Account Type"',       '"اختر نوع الحساب"'),

    # ── Misc labels ──────────────────────────────────────────────────────────
    ('"(Select from table)"',       '"(اختر من الجدول)"'),
    ('"Selected Room:"',            '"الغرفة المختارة:"'),
    ('"Select a product row, then update its selling price and cost."',
     '"اختر منتجاً من الجدول لتعديل السعر والتكلفة."'),
    ('"Clears the notification dedup cache\\nso alerts can show again."',
     '"مسح سجل التنبيهات\\nلتظهر مرة أخرى."'),
    ('"Clears all transactional history (sessions, sales, expenses, invoices) to start a new year. Keeps master data like rooms, products, and customers."',
     '"مسح كل البيانات المالية (الجلسات، المبيعات، المصروفات، الفواتير) لبدء سنة جديدة. يتم الاحتفاظ بالغرف والمنتجات والعملاء."'),
    ('"Over Capacity"',             '"تجاوز السعة"'),
    ('" people but you entered "',  '" شخص لكن أدخلت "'),
    ('"\\nProceed anyway?"',        '"\\nهل تريد المتابعة؟"'),
    ('"✅ Started"',                '"✅ بدأت الجلسة"'),
    ('"✅ Booked"',                 '"✅ تم الحجز"'),
    ('"Confirm"',                   '"تأكيد"'),
    ('"Cancel this booking?"',      '"هل تريد إلغاء هذا الحجز؟"'),
    ('"Direct Sale"',               '"بيع مباشر"'),

    # ── About section ────────────────────────────────────────────────────────
    ('"Version"',       '"الإصدار"'),
    ('"Python"',        '"بايثون"'),
    ('"Framework"',     '"الإطار"'),
    ('"Database"',      '"قاعدة البيانات"'),
    ('"PDF Engine"',    '"محرك PDF"'),
    ('"System"',        '"النظام"'),
]

with open('pages.py', 'r', encoding='utf-8') as f:
    content = f.read()

changes = 0
for old, new in REPLACEMENTS:
    if old in content:
        content = content.replace(old, new)
        changes += 1
    else:
        print(f"NOT FOUND: {old[:60]}")

with open('pages.py', 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n✅ Done! Applied {changes}/{len(REPLACEMENTS)} replacements to pages.py")
